<Project>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <WarningsAsErrors />
    <Deterministic>true</Deterministic>
    <Authors>Danny4897</Authors>
    <Company>AgentScope</Company>
    <Copyright>Copyright © Danny4897 2026</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryUrl>https://github.com/Danny4897/AgentScope</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <Version>0.1.0</Version>
  </PropertyGroup>

  <!-- Enforce code style -->
  <PropertyGroup>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <AnalysisMode>Recommended</AnalysisMode>
  </PropertyGroup>

</Project>
